### ISSUE TITLE
NPM value add

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/entente#101]
Creating this issue as a landing page for ideas about what features we can add/enhance to add more value to npm.

**Comment by lholmquist** [comment]
Something i was thinking about was adding a "plugin" system to NPM.    **Warning, i'm writing this while i'm thinking,  so things might be all over the place**

The idea comes from the ember-cli ecosystem, https://ember-cli.com/ .  I think they also call them blueprints(https://ember-cli.com/extending/#detailed-list-of-blueprints-and-their-use).

basically,  the base `ember` command has a few "commands", like `ember generate`, `ember serve`, etc...

but you can install different plugins to extend/add commands to the `ember` command.  For example, the ember-cli-deploy plugin(http://ember-cli-deploy.com/ , which also has its own plugin system), adds the "deploy" command.  

so you can then do things like `ember deploy production`, which is not available until you install that plugin.

The one difference here, is that these plugins/blueprints are not installed globally, which means they project specific(ember know they are installed because of some keywords in the package.json of the addon)

Where i see something like this useful, is with something like szero,  so instead of having to run a separate command, you could run `npm szero` or something like that.

I suppose this is what the `npm run` command is for, but...  

Or maybe, we could during the "install" of the module, add something to the scripts section of the package.json?  <-- that could be a good option

**Comment by helio-frota** [comment]
This issue can be closed?
