### ISSUE TITLE
Build with node 7x

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/entente#107]
I saw this on roi build:

```
npm ERR! v8-profiler@5.6.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
```

Maybe is good to add node 7 on CI to start looking all bgold projects ?

@lance @lholmquist @balunasj ?

**Comment by lholmquist** [comment]
i want to say yes,  but it did just get released,  and will never be an LTS,  but why not.

**Comment by helio-frota** [comment]
you right, but this can also mean: change 5 to 7 ?
https://raw.githubusercontent.com/nodejs/LTS/master/schedule.png

**Comment by lholmquist** [comment]
👍  lets do it

**Comment by lholmquist** [comment]
related to that error on the v8-profiler module: 
 https://github.com/node-inspector/v8-profiler/issues/99
https://github.com/node-inspector/v8-profiler/issues/98

**Comment by helio-frota** [comment]
From the doc:
"node_abi: The node C++ ABI number. This value is available in Javascript as **process.versions.modules**"
( https://www.npmjs.com/package/node-pre-gyp#versioning )

```
hf@archT440 ~/p/genet ±master⚡ » node
> console.log(process.versions.modules);
51
undefined
> console.log(process.versions);
{ http_parser: '2.7.0',
  node: '7.0.0',
  v8: '5.4.500.36',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '51',
  openssl: '1.0.2j' }
undefined
> 
```

node-pre-gyp ERR! Tried to download(404): 
node-inspector.s3.amazonaws.com/profiler/v5.6.5/node-v**_51_**-linux-x64.tar.gz

The latest is _**48**_

```
<Contents>
<Key>profiler/v5.6.5/node-v48-linux-x64.tar.gz</Key>
<LastModified>2016-05-15T20:27:46.000Z</LastModified>
<ETag>"541c27744673866278a6eee2ec76d7ac"</ETag>
<Size>23321</Size>
<StorageClass>STANDARD</StorageClass>
</Contents>
```

( https://node-inspector.s3.amazonaws.com/ )

**Comment by helio-frota** [comment]
> Listing only the tools / libraries

- [x] opossum
- [x] szero
- [x] huilu
- [x] genet
- [x] roi
- [x] lightbright
- [x] fidelity
- [x] litoria

**Comment by balunasj** [comment]
Hi Helio - I've moved this to Milestone 5, and Lance and I would like you to test these with the more recent updates with Node 7.

**Comment by helio-frota** [comment]
https://github.com/node-inspector/v8-profiler/issues/98#issuecomment-274327673

**Comment by lance** [comment]
@helio-frota that looks like a good solution to this issue. FWIW, Rising Stack is the company that hosts NodeConf Budapest - I think they are a good and responsible bunch who won't leave you in the lurch with an unmaintained dependency.

**Comment by helio-frota** [comment]
> Additional info: 

We need at minimum `ubuntu trusty tahr` on travis:
https://github.com/bucharest-gold/genet/blob/master/.travis.yml#L2

**Comment by helio-frota** [comment]
hey folks I'm going to close this issue because seems lightbright has some things with node 7x
https://github.com/bucharest-gold/lightbright/issues/15
