### ISSUE TITLE
Understand and add fidelity on bluebird benchmark suite

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/entente#109]
1. Due different results from node-bench and benchmark modules
2. This is in consideration in v8 blog:
http://v8project.blogspot.com.br/2016/07/v8-release-53.html

> ES6 Promise performance
> V8's performance on the Bluebird ES6 Promise benchmark suite improved by 20-40% in V8 version 5.3, varying by architecture and benchmark.
>

**Comment by helio-frota** [comment]
The idea is to create a directory `suite` on `fidelity/benchmark/`, copy/past the suite related code, and run fidelity on that suite.

**Comment by lance** [comment]
@helio-frota it would be great if we could submit a PR to bluebird and get fidelity included in the benchmarks https://github.com/petkaantonov/bluebird/tree/master/benchmark

**Comment by helio-frota** [comment]
@lance :+1: 
But the `analysis` directory has a test just for one implementation, maybe is good to have to track Fidelity performance.

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/fidelity/issues/22
