### ISSUE TITLE
Info about the Hawkular fragments attributes

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/entente#11]
We need to have at least a basic idea about the meaning to be able to: 
- [x] See the result using hawkular-ui
- [x] The minimum of the data working like the screenshots

https://hawkular.gitbooks.io/hawkular-apm-user-guide/content/apiref/rest-apm.html#_fragments

**Comment by helio-frota** [comment]
| Attribute | Info |
|----------|:-------------:|
| { nodes: [ { operation } ] } |  GET, POST, etc... |

**Comment by helio-frota** [comment]
For the `{ nodes: [ { operation } ] }` maybe possible to get from: 

```
  handle: 
   HTTPParser {
      Socket {
      ClientRequest {
        method: 'GET',  <---------------
```

This works for a client but for a server - [using this example](https://github.com/panther-js/lbe) - we don't have HTTPParser

**Comment by helio-frota** [comment]
``` javascript
 let traces = [{
    'id': 'd07c2b20-a77c-45a3-ae27-278a65a7233e',
    'startTime': new Date().getTime(),
    'businessTransaction': 'testhttp',
    'hostAddress': '127.0.0.1',
    'nodes': [{
      'type': 'Producer',
      'uri': '/sayHello',
      'operation': 'GET',
      'baseTime': 28254188696110,
      'duration': 9074249,
      'endpointType': 'HTTP'}]}];
```

**Comment by helio-frota** [comment]
**Using this ^ data:**

![a](https://cloud.githubusercontent.com/assets/6443576/17532923/1d23398c-5e59-11e6-9850-13af3b31a400.png)

![b](https://cloud.githubusercontent.com/assets/6443576/17532931/26e29d64-5e59-11e6-9eb8-bdd1d4e74be4.png)

**Comment by helio-frota** [comment]
**Aditional valuable information:**

```
<helio-frota> folks quick question about hawkular-apm : what means 'baseTime' ?
<helio-frota> nodes -> baseTime on hawkular-apm-server
<helio-frota> if I remove this attribute , the node becomes green
<gbrown> helio-frota it is effectively the start time
<helio-frota> gbrown, thanks! so the startTime must to be the same value ?
<gbrown> helio-frota do you mean you don't include the field in the reported data, resulting in the aggregated distributed tracing diagram showing green for the service node
<helio-frota> https://cloud.githubusercontent.com/assets/6443576/17532931/26e29d64-5e59-11e6-9eb8-bdd1d4e74be4.png
<helio-frota> gbrown, yes ^
<helio-frota> this shows green if not include this attribute for the version 0.9.0
<gbrown> helio-frota my guess would be that it is calculating the duration for the node as zero, and therefore it doesn't see it as a performance bottleneck
<helio-frota> gbrown, thanks for the info! but, so startTime is === baseTime ?
<gbrown> helio-frota no - startTime is number of milliseconds since epoch, but baseTime is nanoseconds
<gbrown> helio-frota so the baseTime plus duration is to understand the different time scope of the nodes in the hierarchy - where the top level node's baseTime would be the same point in time as the startTime
<gbrown> of the fragment
<gbrown> helio-frota just so you are prepared, there are some minor REST API changes coming in the next release for reporting fragments. Next release should hopefully be in a couple of weeks (just need to review outstanding jiras) and then after that hopefully will be stable
```

**Comment by helio-frota** [comment]
I'm using this 'APP': https://github.com/panther-js/lbe

[To not add a example directory inside hawkular-apm-client and to have a clean fake-app using lightbright and hawkular-apm-client for experiments]

Using only plain lightbright, and calling lightbright.disable() we can see:

```
[ { id: 1,
    startTime: 1471981111330,
    businessTransaction: 'GetAddrInfoReqWrap',
    hostAddress: '192.168.2.103',
    nodes: [ [Object] ] },
  { id: 2,
    startTime: 1471981111330,
    businessTransaction: 'TCP',
    hostAddress: '192.168.2.103',
    nodes: [ [Object] ] } ]
```

Removing lightbright.disable(), starting the app again and for **the second time** calling the app we can see more data/handlers etc:

> The first time accessing the url we can see the same result when calling lightbright.disable()

```
[ { id: 1,
    startTime: 1471981347835,
    businessTransaction: 'GetAddrInfoReqWrap',
    hostAddress: '192.168.2.103',
    nodes: [ [Object] ] },
  { id: 2,
    startTime: 1471981347835,
    businessTransaction: 'TCP',
    hostAddress: '192.168.2.103',
    nodes: [ [Object] ] } ]
[ { id: 1,
    startTime: 1471981352091,
    businessTransaction: 'GetAddrInfoReqWrap',
    hostAddress: '192.168.2.103',
    nodes: [ [Object] ] },
  { id: 2,
    startTime: 1471981352091,
    businessTransaction: 'TCP',
    hostAddress: '192.168.2.103',
    nodes: [ [Object] ] },
  { id: 8,
    startTime: 1471981352091,
    businessTransaction: 'HTTPParser',
    hostAddress: '192.168.2.103',
    nodes: [ [Object] ] },
  { id: 8,
    startTime: 1471981352091,
    businessTransaction: 'HTTPParser',
    hostAddress: '192.168.2.103',
    nodes: [ [Object] ] },
  { id: 8,
    startTime: 1471981352091,
    businessTransaction: 'HTTPParser',
    hostAddress: '192.168.2.103',
    nodes: [ [Object] ] },
  { id: 9,
    startTime: 1471981352091,
    businessTransaction: 'Zlib',
    hostAddress: '192.168.2.103',
    nodes: [ [Object] ] },
  { id: 11,
    startTime: 1471981352091,
    businessTransaction: 'WriteWrap',
    hostAddress: '192.168.2.103',
    nodes: [ [Object] ] },
  { id: 9,
    startTime: 1471981352091,
    businessTransaction: 'Zlib',
    hostAddress: '192.168.2.103',
    nodes: [ [Object] ] },
  { id: 12,
    startTime: 1471981352091,
    businessTransaction: 'WriteWrap',
    hostAddress: '192.168.2.103',
    nodes: [ [Object] ] },
  { id: 10,
    startTime: 1471981352091,
    businessTransaction: 'Timer',
    hostAddress: '192.168.2.103',
    nodes: [ [Object] ] } ]
```

to reproduce just clone the fake-app , then npm install and npm start.
access http://localhost:3000/hail

**Comment by helio-frota** [comment]
New version:

https://github.com/hawkular/hawkular-apm/releases/tag/0.10.0.Final

**Comment by balunasj** [comment]
@helio-frota Assigned to you, since you're obviously the most active :-) 

What do you consider the end state for this issue?  Getting a similar issue into Lightbright and then closing?  Or something else?

**Comment by helio-frota** [comment]
Good question.
I'm going to review the new version of [hawkular-apm-server](https://github.com/hawkular/hawkular-apm/releases/tag/0.10.0.Final).
To check if still able to see the results using hawkular-ui, then close this issue.

The task on the first comment: 
'Populate the json object using lightbright.'
Can be removed because is the same as:
https://github.com/bucharest-gold/entente/issues/7

**Comment by helio-frota** [comment]
makes me a little worried:
released this on **Aug 24** · **115 commits to master since this release**

**Comment by helio-frota** [comment]
I'm using this: 
https://github.com/jboss-dockerfiles/hawkular/tree/master/hawkular-apm-server-dev
tip from gbrown on hawkular irc channel.

working fine :

```
  Should add traces.
    { endpoint: 'http://localhost:8080/hawkular/apm/traces/fragments',
      username: 'jdoe',
      password: 'password' }
    { statusCode: 200,  <--------------------------------------
```

The new endpoints have `/traces/` path.

To close this issue we need to see the results on hawkular-ui like
the screenshot: https://github.com/bucharest-gold/entente/issues/11#issuecomment-238685692

**Comment by helio-frota** [comment]
![a](https://cloud.githubusercontent.com/assets/6443576/19084107/897d8d18-8a3b-11e6-9246-f80cfa20cede.png)

**Comment by lance** [comment]
@helio-frota I'm probably a little slow on the uptake here (you know, concussion and all :), but can you please summarize each attribute of the trace data that needs to be sent to hawkular? What is its type, what is the semantic meaning, is it required or not, etc?

**Comment by helio-frota** [comment]
@lance Ok!
I closed this issue to try to organize a bit. 
The idea was just to put thing to work again, and about the attributes:
"The minimum of the data working like the screenshots"
https://github.com/bucharest-gold/entente/issues/11#issue-169233677

So, currently I'm not totally able [yet] to answer your question, but I'll do on this issue:
https://github.com/bucharest-gold/entente/issues/7

Because is related to " Finish the data mapping between lightbright and hawkular-apm json."
