### ISSUE TITLE
Add projects to awesome node

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/entente#111]
https://github.com/sindresorhus/awesome-nodejs

**Comment by lance** [comment]
Didn't you submit a PR for this? What's the status?

**Comment by helio-frota** [comment]
Yes - status waiting

**Comment by lance** [comment]
Can you link it please?

**Comment by helio-frota** [comment]
sure: https://github.com/sindresorhus/awesome-nodejs/pull/623

**Comment by lance** [comment]
I think we can close this, right? You've submitted a PR. Judging by the outstanding PRs on that repo, it could be a while before yours is merged. I don't think we need to keep this open until then. Feel free to reopen if you disagree.

**Comment by helio-frota** [comment]
right!
