### ISSUE TITLE
Add Sub Zero Grunt plugin

### ISSUE THREAD

**Issue by danbev** [bucharest-gold/entente#112]
We have number of projects that use Grunt and these project might like to use szero. This is a suggestion to add such a plugin. 

An initial plugin can be found here:
https://github.com/danbev/szero-grunt

**Comment by helio-frota** [comment]
so, the best way is to move for bgold ?
if yes, +1 for me.

**Comment by danbev** [comment]
@helio-frota Sounds good moving it to a bgold repository. Let me know if this is something you all agree on and if so please create the repo and I'll issue a PR against it. Thanks

**Comment by lholmquist** [comment]
While we(BGOLD) aren't using grunt, there are other projects inside RHT that are using it, like @danbev said,  so i think making this a bgold repo would be ok. i think it make it more "official" 

So +1

**Comment by lholmquist** [comment]
@danbev added here

https://github.com/bucharest-gold/szero-grunt

**Comment by danbev** [comment]
@helio-frota @lholmquist Thanks guys!
