### ISSUE TITLE
npm-init.js installing szero 0.5.1

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/entente#114]
```
"szero": "^0.5.1",
```

**Comment by helio-frota** [comment]
we need at least 0.7.0, because is really a better version.

**Comment by lholmquist** [comment]
yea, i agree,  but should we wait until 0.8.0 is released, which i think i have scheduled for this friday, https://github.com/bucharest-gold/szero/milestone/6

it will fix that bug with the unused dependencies,  https://github.com/bucharest-gold/szero/issues/61

**Comment by helio-frota** [comment]
great !

**Comment by lholmquist** [comment]
actually lets use 0.7.1,  it has that bug fix,  i moved the 0.8.0 release to december since there is a bit more too it.  and i would like to take some time to figure it out.

**Comment by lholmquist** [comment]
landed here:  98a1351
