### ISSUE TITLE
NPM involment

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/entente#12]
I know we are also focused on Node core involvement, but we should possibly also take a look at npm and its issues. https://github.com/npm/npm/issues

considering this is "the" way to interact with node modules.

My tweet asking npmjs were to start:  https://twitter.com/sienaluke/status/758330112047779840

This was also a good primer on npm and some of its usage, https://youtu.be/hopWbVKmiVQ?list=PLfMzBWSH11xZWvE3iuTw6tdzp90gnODdp

**Comment by lholmquist** [comment]
Currently have an open PR for an issue regarding docs for the npm-init interviewer,

https://github.com/npm/npm/issues/13005

**Comment by lholmquist** [comment]
## @lholmquist

### npm/npm
- [Commits](https://github.com/npm/npm/commits/master?author=lholmquist)
- [Comments](https://github.com/npm/npm/issues?utf8=%E2%9C%93&q=commenter%3Alholmquist)
- [Open PRs](https://github.com/npm/npm/pulls/lholmquist)
- [Closed PRs](https://github.com/npm/npm/pulls?q=is%3Apr+author%3Alholmquist+is%3Aclosed)

### npm/docs
- [Commits](https://github.com/npm/docs/commits/master?author=lholmquist)
- [Comments](https://github.com/npm/docs/issues?utf8=%E2%9C%93&q=commenter%3Alholmquist)
- [Open PRs](https://github.com/npm/docs/pulls/lholmquist)
- [Closed PRs](https://github.com/npm/docs/pulls?q=is%3Apr+author%3Alholmquist+is%3Aclosed)

**Comment by lholmquist** [comment]
Link to the commit from the PR i had for this [issue](https://github.com/npm/npm/issues/14009), https://github.com/npm/npm/commit/bf3bd1e4347ee2c5de08d23558c4444749178c8b

**Comment by lholmquist** [comment]
The docs update PR that is above, is now merged and scheduled for the next release!

**Comment by helio-frota** [comment]
## @helio-frota

### npm/npm
- [Commits](https://github.com/npm/npm/commits/master?author=helio-frota)
- [Comments](https://github.com/npm/npm/issues?utf8=%E2%9C%93&q=commenter%3Ahelio-frota)
- [Open PRs](https://github.com/npm/npm/pulls/helio-frota)
- [Closed PRs](https://github.com/npm/npm/pulls?q=is%3Apr+author%3Ahelio-frota+is%3Aclosed)

#### npm/npmlog
- [Commits](https://github.com/npm/npmlog/commits/master?author=helio-frota)
- [Comments](https://github.com/npm/npmlog/issues?utf8=%E2%9C%93&q=commenter%3Ahelio-frota)
- [Open PRs](https://github.com/npm/npmlog/pulls/helio-frota)
- [Closed PRs](https://github.com/npm/npmlog/pulls?q=is%3Apr+author%3Ahelio-frota+is%3Aclosed)

#### npm/nopt
- [Commits](https://github.com/npm/nopt/commits/master?author=helio-frota)
- [Comments](https://github.com/npm/nopt/issues?utf8=%E2%9C%93&q=commenter%3Ahelio-frota)
- [Open PRs](https://github.com/npm/nopt/pulls/helio-frota)
- [Closed PRs](https://github.com/npm/nopt/pulls?q=is%3Apr+author%3Ahelio-frota+is%3Aclosed)

#### npm/fs-vacuum
- [Commits](https://github.com/npm/fs-vacuum/commits/master?author=helio-frota)
- [Comments](https://github.com/npm/fs-vacuum/issues?utf8=%E2%9C%93&q=commenter%3Ahelio-frota)
- [Open PRs](https://github.com/npm/fs-vacuum/pulls/helio-frota)
- [Closed PRs](https://github.com/npm/fs-vacuum/pulls?q=is%3Apr+author%3Ahelio-frota+is%3Aclosed)

**Comment by lance** [comment]
Closing - out of date
