### ISSUE TITLE
Add swagger UI to MSA demo app

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#123]
All of the other microservices in the helloworld msa app expose their API via swagger. The node app should do the same.

Ref: https://cdn.rawgit.com/redhat-helloworld-msa/helloworld-msa/master/readme.html

**Comment by lance** [comment]
https://github.com/redhat-helloworld-msa/bonjour/pull/8

**Comment by lance** [comment]
Apparently this contribution had a negative impact on the keycloak authenticated route. It has been reverted and my contributions have been moved to a branch. I need to figure out what's going wrong here and fix it.

Ref: https://github.com/redhat-helloworld-msa/bonjour/compare/refactor

**Comment by lance** [comment]
@lholmquist is working on this

**Comment by lholmquist** [comment]
"Chase in on the case".  Sorry, been watching to much Paw Patrol with the kids :)

**Comment by lholmquist** [comment]
The PR i sent that fixes the issues with Keycloak has been merged,  https://github.com/redhat-helloworld-msa/bonjour/pull/13

I just want to update the link to the swagger docs to be the root of the service, similiar to the other services, before closing

**Comment by lholmquist** [comment]
This should be all set now,  https://github.com/redhat-helloworld-msa/bonjour/pull/14
