### ISSUE TITLE
Release 0.4.0 of Opossum

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#124]
This release should include a full-featured browser example that illustrates how the circuit breaker pattern works.

**Comment by lance** [comment]
Actually ended up going all the way to 0.5.0.

Opossum now includes

* Supply a `CircuitBreaker` as a fallback action
* Full browser support
* Complete jQuery example application

Yay!

https://github.com/bucharest-gold/opossum/releases/tag/v0.5.0

**Comment by helio-frota** [comment]
yay !
