### ISSUE TITLE
Explore the communication between the layers of the Node.js

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/entente#125]

**Comment by balunasj** [comment]
The output of this issue should be a blog post on the different layers, how they interact, and things to keep in mind.

**Comment by helio-frota** [comment]
For future research:

http://www.nearform.com/nodecrunch/developer-initiates-io-operation-wont-believe-happens-next/

**Comment by helio-frota** [comment]
The first part is related, but not directly:
https://helio-frota.github.io/post/exploring-nodejs-layers/
https://helio-frota.github.io/post/exploring-nodejs-layers-1-5/

**Comment by helio-frota** [comment]
This is related:
https://helio-frota.github.io/post/exploring-nodejs-layers-2/

**Comment by balunasj** [comment]
@helio-frota I think we can mark this issue completed for now, as we discussed it's at a natural stopping point, and the blogs you've put our are great!
