### ISSUE TITLE
Build and publish Openshift Node.js Base Images

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#126]
I have forked Ryan's repository which has been used to create unofficial Node.js builder images for Openshift Origin (v3). We should use and modify this repository in the following ways.

- [x] The Makefile specifies the namespace for publishing to Docker Hub. Create a bucharest-gold Docker Hub account and use a bucharest-gold namespace for publishing these images.

- [x] Set up continuous integration for this repository. Be sure that publishing to Docker Hub is _not_ a part of this process.

- [x] Modify the build so that the default is to not publish to Docker Hub (if I read the code right, this is the case).

- [x] Update the Node.js version targets to current releases. The latest versions for each main line can be found here: https://nodejs.org/en/download/releases/

- [ ] Publish images to Docker Hub for each of the Node.js releases. Be sure to tag the GitHub repository with versions for these releases (not the Node.js version, but versions for the published images).

- [ ] Update the README.md file to reflect new values for namespaces and versions.

- [ ] Document a set of conditions and steps for releasing new images as soon as possible after a Node.js version release/update. This should be automated with Make/NPM or whatever as much as possible, but how and when to do it are important to document. At the moment, 'make build all' will do this, I believe.

- [ ]  The build process is a little confusing. It goes from NPM to Make to NPM and then to shell scripts. This could maybe be simplified.

- [ ] Test building OpenShift applications using these new builds.

- [ ] Update 'bonjour' app from the MSA Demo to use the most current of these images.

- [ ] Document and/or blog about how to easily use these images on OpenShift to have the latest Node versions in your application. Maybe show how to migrate a Node.js 6.x application on OpenShift to a Node.js 7.x application.

**Comment by lholmquist** [comment]
@lance what is the link to the s2i repo(fork)?

**Comment by lance** [comment]
https://github.com/bucharest-gold/origin-s2i-nodejs

**Comment by lance** [comment]
As a reference, here is a link to the SCL images https://github.com/sclorg/s2i-nodejs-container

**Comment by lance** [comment]
Organization created. I've added @lholmquist as a member. Do you have a docker hub ID @helio-frota?

https://hub.docker.com/u/bucharestgold/

**Comment by helio-frota** [comment]
@lance created: `heliofrota`

**Comment by helio-frota** [comment]
> Set up continuous integration for this repository. Be sure that publishing to Docker Hub is not a part of this process.

This means `make test` part ?
if yes: https://travis-ci.org/helio-frota/origin-s2i-nodejs/builds/199390885 ]
we can use this [unpolished travis file](https://github.com/helio-frota/origin-s2i-nodejs/blob/ci-foo/.travis.yml) for now ?
Also we need your branch `lance-macos` merged into master because is not currently possible to run on master due a weird error.

**Comment by lance** [comment]
@helio-frota my changes were merged yesterday https://github.com/ryanj/origin-s2i-nodejs/compare/master...bucharest-gold:master. What error are you getting?

**Comment by helio-frota** [comment]
@lance oops, I was very late in posting the feedback here.

**Comment by lance** [comment]
All of the checkpoints above are replicated in https://github.com/bucharest-gold/origin-s2i-nodejs/issues. Closing this for now.
