### ISSUE TITLE
NPM init script should use up to date dependency versions

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#127]
At the moment, we don't have a good way to keep our dependencies up to date. The script itself installs dependencies that I think are probably already out of date. And then once you've got `~/.npm_init.json` installed, it has dependencies that don't remain up to date.

I recommend at a minimum, we find a better way to do the installation so that we're not starting with stale dependencies. I think this would probably mean changing from a shell script to a node cli app that you can install as a global NPM module.

I also think that improving NPM itself so that there is a good way to make `npm init` smarter about default dependency versions would be a good contribution to the project.

**Comment by lholmquist** [comment]
I think originally we had the dependencies as `*`, so it would get the latest versions.  i wonder if we go back to that?   Not sure i really like that idea though.

The cli app idea might work.  the ux of getting/using/updating the cli app might be a little easier than  that of the init script.  With the init script, you need to clone the repo, and do some copy pasting,  with a cli app, you can just do `npm install`

**Comment by lholmquist** [comment]
We also discussed that we could trigger an `npm update` which should get the latest versions of packages we are using, and then install them.

**Comment by helio-frota** [comment]
So we are going to make a CLI and publish ?

**Comment by helio-frota** [comment]
>  I think this would probably mean changing from a shell script to a node cli app that you can install as a global NPM module.

:+1:

**Comment by helio-frota** [comment]
started on this repo: https://github.com/bucharest-gold/bgold

**Comment by helio-frota** [comment]
I'm going to close this issue. 
The project has been archived and we are not focused on this anymore.
