### ISSUE TITLE
Hystrix Metrics Event Stream

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/entente#128]
Related to https://github.com/redhat-helloworld-msa/bonjour/issues/16 

We should look in to adding this type of reporting to Opposum,

**Comment by lholmquist** [comment]
We will need to have our event stream output data like this:  https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-metrics-event-stream

**Comment by lance** [comment]
@lholmquist  Can this be closed?

**Comment by lholmquist** [comment]
I think so.
