### ISSUE TITLE
Review/Update Infinispan client

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/entente#13]

**Comment by lance** [comment]
Was this opened at someone's (galderz) request? What is the motivation?

**Comment by helio-frota** [comment]
The motivation is to update node version and replace vars with let
construção, add some es6 features

Em 17/08/2016 8:27 AM, "Lance Ball" notifications@github.com escreveu:

**Comment by helio-frota** [comment]
Let and const not construção - [dumbphone here]

Em 17/08/2016 8:59 AM, "Helio Frota" 00hf11@gmail.com escreveu:

**Comment by helio-frota** [comment]
node 0.10 until October
node 0.12 until December
https://raw.githubusercontent.com/nodejs/LTS/master/schedule.png

**Comment by helio-frota** [comment]
node 0.12 until December , then milestone 4

**Comment by balunasj** [comment]
Its possible this is an abandoned client library.  @balunasj will followup with stakeholders on this.  In the mean time, lets move this to unscheduled.

**Comment by helio-frota** [comment]
Also , updating the motivation:

"Apply bucharest-gold guidelines"

**Comment by helio-frota** [comment]
closing, we can open again on future in case needed.
