### ISSUE TITLE
Create a Node.js Microservices Demo

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#132]
The existing [Red Hat Hello World MSA Demo](https://cdn.rawgit.com/redhat-helloworld-msa/helloworld-msa/master/readme.html) is a fantastic introduction to the wide ranging µ-services capabilities Red Hat has to offer. However, for the purposes of showing off our Node.js µ-services capabilities, it's not a perfect fit. As a long-term goal, I would like to see us develop a more full-featured µ-service demo that really highlights Node.js workflows and practices. The application itself should be more than a "hello world". 

***** Everything that follows is just rough draft *****

# Demo application overview
Instead of a basic "hello world" demo, how about something like a weather app.

* Front end (browser/mobile) accesses weather service through an API gateway at /weather/<zip>. This request receives a JSON response such as:

````json
{ "zip": <zip>,
     "current_temperature": <temp>,
     "forecast": [
        { "date": <date>, "high": <temp>, "low": <temp> } ] }
````

* The API gateway converts `/weather/<zip>` to `/temperature/<zip>` and `/forecast/<zip>`, each of which is its own service.

* Each of these services are simple node.js applications. Bonus points if they use Seneca.js and the SWIM transport protocol for automatic service discovery.

* All services feed into they Hystrix dashboard. We can reuse the existing MSA demo image for the dashboard, and just feed our own Hystrix data stream to it. (Opossum has yet to be implemented with Hystrix data streams, but that should happen).

* The demo includes zipkin integration similar to what is in the MSA demo now. This could probably be mostly reused, as-is.

* Users should be able to login via keycloak integration, and the experience is somehow modified, e.g. historical data downloads are available after login.

**Comment by lance** [comment]
Project underway at https://github.com/lance/node-msa/demo

**Comment by lholmquist** [comment]
the real link . https://github.com/lance/node-msa-demo :)

**Comment by lance** [comment]
This issue is out of date. Closing.
