### ISSUE TITLE
origin-s2i-repo versioning

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/entente#135]
This issue is around how we should be versioning the actual code in the https://github.com/bucharest-gold/origin-s2i-nodejs repo.

Our versions(tags) we publish to docker hub are the actual node.js versions.  But we need some sort of versioning for the code in the actual repo.

Some questions to answer

* How do we version the repo itself? what constitutes a major, minor and patch level version bump?
* Do we do a major version bump every time we publish a new major version of node?
*  A minor for every minor?
* A patch for every patch?

**Comment by lance** [comment]
https://github.com/bucharest-gold/origin-s2i-nodejs/blob/master/RELEASING.md
