### ISSUE TITLE
QCon Sao Paulo talk

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#139]
Slides and other materials for the qcon talk. April 22.

**Comment by lance** [comment]
http://lanceball.com/qcon-saopaulo-2017/

https://github.com/lance/qcon-saopaulo-2017

**Comment by lance** [comment]
@helio-frota @balunasj @lholmquist do you guys mind taking a look at these slides (link above) and providing any feedback you might have? Thanks!

I assigned you all to the task, feel free to remove yourself as an assignee if you don't have the bandwidth to do this. :)

**Comment by helio-frota** [comment]
LGTM :+1: 
found only one typo: https://github.com/lance/qcon-saopaulo-2017/pull/1
