### ISSUE TITLE
Node Core Module Exploration

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/entente#14]
This is an idea i had for a blog series.  It is sort of a reference for me since there are some modules that i am not to familiar with.

This also goes along with the talk i submitted for Empirenode about "The node core modules less traveled"

i'm basically going to go straight down the list on the docs page:

https://nodejs.org/dist/latest-v6.x/docs/api/
### Current Post

Assert - http://blog.lholmquist.org/node-core-modules-exploration/
Buffers - http://blog.lholmquist.org/node-core-modules-exploration-buffers/

**Comment by lholmquist** [comment]
C/C++ Addons - http://blog.lholmquist.org/node-core-modules-exploration-cc-addons/

**Comment by lholmquist** [comment]
Next post is up on Child Processes - http://bit.ly/2bOP3jc

**Comment by lholmquist** [comment]
I'm going to break this into smaller chunks so i can assign milestones to those individual items, and it will be easier to track the modules that still need to be explored

**Comment by lholmquist** [comment]
closing and will track with all the other "node core exploration" issues

**Comment by lholmquist** [comment]
Reopening with a list of the Blogs to be done

- [X] Assert - http://blog.lholmquist.org/node-core-modules-exploration/
- [X] Buffers - http://blog.lholmquist.org/node-core-modules-exploration-buffers/
- [X] C/C++ Addons - http://blog.lholmquist.org/node-core-modules-exploration-cc-addons/
- [X] Child Processes - http://bit.ly/2bOP3jc
- [X] Cluster -  http://bit.ly/2e7RwYM
- [X] Command Line Options - http://bit.ly/2eoBgmt
- [X] Console - http://bit.ly/2fcRwFZ
- [X] Crypto - http://bit.ly/2h9RUFK
- [X] Debugger - http://blog.lholmquist.org/node-core-modules-exploration-debugger/
- [X] DNS -  http://blog.lholmquist.org/node-core-modules-exploration-dns/
- [ ] Domain
- [ ] Errors
- [ ] Events
- [ ] File System
- [ ] Globals
- [ ] HTTP/HTTPS
- [ ] Modules
- [ ] Net
- [ ] OS
- [ ] Path
- [ ] Process
- [ ] Punycode
- [ ] Query Strings
- [ ] Readline
- [ ] REPL
- [ ] Stream
- [ ] String Decoder
- [ ] Timers
- [ ] TLS/SSL
- [ ] TTY
- [ ] UDP/Datagram
- [ ] URL
- [ ] Utilities
- [ ] V8
- [ ] VM
- [ ] ZLIB

**Comment by lance** [comment]
Closing - out of date
