### ISSUE TITLE
Blog on libuv licensing, community and contribution options

### ISSUE THREAD

**Issue by balunasj** [bucharest-gold/entente#143]
Basically a "beginners guide to...." including licensing around libuv, it's community, and the ability to submit and review patches, etc...

libuv is a cross platform C library for asynchronous I/O. It provides the asynchronous operations exposed by Node.js. You can read more about libuv here http://libuv.org/ and here http://docs.libuv.org/en/v1.x/. Copyright is held by Joyent, Inc.

Node.js issues related to libuv are here https://github.com/nodejs/node/issues?q=is%3Aopen+is%3Aissue+label%3Alibuv

Lower priority item

**Comment by helio-frota** [comment]
This issue can be closed?

**Comment by lance** [comment]
Closing - out of date
