### ISSUE TITLE
Move node-rpm to bucharest-gold organization

### ISSUE THREAD

**Issue by danbev** [bucharest-gold/entente#144]
This repository is currently private and should be moved into the bucharest-gold org:
https://github.com/danbev/node-rpm

Not sure about the name of the repository and if it should change to something else perhaps. 

After moving this the CI configuration (.travis.yml) must be updated so that the publishing works after tagging.

The tags should also be recreated.

**Comment by balunasj** [comment]
Review if there is a naming convention to follow, possibly to align with Fedora if that would be helpful?

**Comment by danbev** [comment]
I ran into an issue when moving with has to do with Travis CI. I've been using trail since this repo was on my private github and that seemed to allow for build time of  max 120 mins. The free edition seems to have a max build time off 50 mins which is not enough for ours to complete. I'm looking into what options we have regarding this.

**Comment by danbev** [comment]
I think I'll close this issue and create a new one to address the build time. I've got an idea that we can create a base image for our builds that has compiled the complete code base. After this will can use tags to update and the build instead of downloading a complete source distribution and compiling it again. At least I think that would be worth a shot.
