### ISSUE TITLE
Review existing appdev.openshift.io setup and boosters

### ISSUE THREAD

**Issue by balunasj** [bucharest-gold/entente#145]
See http://openshiftio-appdev-docs-appdev-documentation.tsrv.devshift.net/getting-started.html for details.

**Comment by lholmquist** [comment]
another options http://appdev.openshift.io/getting-started.html

**Comment by lholmquist** [comment]
I've been writing down some notes as i've been going through,  i need to start organizing those

**Comment by lholmquist** [comment]
We talked about this in the last meeting and now have a plan of action going forward which is to start with an openshift-client to do node builds/deploys #154 which will also lead into a test framework #151 

closing
