### ISSUE TITLE
Review AppDev repositories, and release structure/process

### ISSUE THREAD

**Issue by balunasj** [bucharest-gold/entente#146]
See https://github.com/openshiftio for the repos, and the release process is https://docs.google.com/document/d/1_dcpb6Xd6Do6n2BJrwJj0uBr_lQp_hIY91BwhdEkIDc/edit#heading=h.cgc58jz1uk

**Comment by lance** [comment]
@lholmquist @balunasj can this be closed now that we have integrated with RHOAR?

**Comment by lholmquist** [comment]
yea, we can probably close this now
