### ISSUE TITLE
Benchmark and profile usage/view workflow

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/entente#15]
- [ ] Write the steps to run benchmarks in our node modules.
- [ ] Write the steps to run profile and see the results on chrome dev tools.

**Comment by balunasj** [comment]
Can you add a little more detail or update the summary?  For example what is the output, a blog, doc, etc...?

**Comment by helio-frota** [comment]
> Attempting to use plot-timer-events to generate a graph of v8.log

*python2.7 required*

git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

export PATH=`pwd`/depot_tools:"$PATH"

fetch v8

[hf@archT440 v8]$ du -s -h
1.6G

node -p process.versions.v8

git branch --remotes | grep branch-heads/

git checkout branch-heads/5.0

cd v8/ 

gclient sync

```
tiny hack 1:
cd /usr/lib/
sudo ln -s libtinfo.so.6 libtinfo.so.5
```
```
tiny hack 2:
vim Makefile
GYPFLAGS += -Dlinux_use_bundled_gold=0
[ inspired by :https://bbs.archlinux.org/viewtopic.php?pid=1610923#p1610923 ]
```

make native

export D8_PATH=`pwd`/out/native/

[hf@archT440 v8]$ tools/plot-timer-events --distortion=4500 ~/isolate-0x23d4dc0-v8.log 
         line 0: undefined variable: Infinity

**Comment by lance** [comment]
@helio-frota can you explain a little about what the plot-timer-events tool shows, and how we can use it to optimize our tools/modules?

**Comment by helio-frota** [comment]
@lance currently no. :]
[not yet]

I was thinking this plot-timer will show javascript part.
Maybe is good to create another issue like this: #24 

This issue here I was thinking to keep the focus on javascript
So for now the idea is just document a bit about benchmark module
and the steps to see 'node --prof' on chrome-dev-tools.
[ otherwise I think it can take a long time ]

But what you think ?

**Comment by helio-frota** [comment]
@balunasj hi,

We don't need this issue anymore :]. 
Now we have a tool https://github.com/bucharest-gold/genet.
