### ISSUE TITLE
Openshift testing framework for node.js

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#151]
Currently, testing an application in an openshift environment is kind of hackey. We do it in the origin [test target](https://github.com/bucharest-gold/origin-s2i-nodejs/blob/master/test/run), but it would be nice if we could abstract this a bit, and make it more generally usable.

The wildfly booster tests use something in the io.openshift package, but I'm not sure yet what this is. 
https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-rest-http/blob/master/src/test/java/io/openshift/booster/OpenshiftIT.java#L23

**Comment by lholmquist** [comment]
This is the repo for those test-utils: https://github.com/openshiftio/booster-common/blob/master/openshift-test-utils/src/main/java/io/openshift/booster/test/OpenShiftTestAssistant.java

Which is using a fabric8 project: https://github.com/fabric8io/kubernetes-client

I was able to run the tests using ` mvn clean verify -Popenshift,openshift-it`

I needed to first run an `oc login` and point to the project where the integration tests would execute.  I have an instance of minishift running locally

**Comment by lholmquist** [comment]
Looking at this issue, https://github.com/openshiftio/booster-common/issues/8 the OpenshiftTestAssistent.java from the link above was a temporary solution and they are looking to move away from it.  I will take a look at some the links in that issue to see where they are going

**Comment by helio-frota** [comment]
@lholmquist good follow up. Is good to know that they have some concerns/warnings on this approach.

**Comment by helio-frota** [comment]
I'm not 100% sure but from what I understood it is not possible yet to run minishift on travis:
https://github.com/minishift/minishift/issues/1108
https://github.com/minishift/minishift/issues/144
https://github.com/minishift/minishift/issues/1229#issuecomment-320301971

**Comment by helio-frota** [comment]
progress! 
https://travis-ci.org/bucharest-gold/mean-booster/builds/289038920#L1287

**Comment by lance** [comment]
I wonder if we can consider this closed now that we have `rhoaster`. @lholmquist @helio-frota your thoughts?

**Comment by lholmquist** [comment]
I think it makes sense to close now that we have `rhoaster`
