### ISSUE TITLE
Node 8 S2I, RPM updates

### ISSUE THREAD

**Issue by balunasj** [bucharest-gold/entente#159]
Updates for our S2I images, RPMs for Node 8 release coming soon

**Comment by lance** [comment]
@balunasj is this for the centos7-s2i-nodejs images? If so, I think it can be closed - though we don't depend on the RPMs for this. Or do you want to produce another set of images that uses the RPMs and runs Fedora?

**Comment by balunasj** [comment]
Yup, so it's all set! :-)
