### ISSUE TITLE
Node Crypto Interface

### ISSUE THREAD

**Issue by danbev** [bucharest-gold/entente#160]
The goal of this issue is to extract an initial interface for crypto in Node.js. We want to do this so that we can support multiple versions/vendors of crypto libraries. 

This task should investigate options for such an interface and how it can be used with Node.js. At the moment OpenSSL is quite tightly coupled with Node.js and part of this task should be to look at viable options.

The idea is to start small and look at one or two functions that are used from src/node.cc. The idea at the moment is to have a CryptoFactory that handles registering/unregistering crypto providers and handles the creation of Crypto instances. We are currently in the process or trying this out and might find better solutions as we try this out in practice. On issue is how should these different providers register with the factory etc.

After this investigation and pushing a branch with an example this task can be considered closed and we will open an issue on Node's github repository and continue work there.

**Comment by danbev** [comment]
Created a pull request for this:
https://github.com/nodejs/node/pull/13575

**Comment by helio-frota** [comment]
This issue can be closed?

**Comment by danbev** [comment]
Closing as this is out of date.
