### ISSUE TITLE
Fix organization privileges for bucharestgold

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#162]
Specifically to allow @lholmquist and @hfrota to manage greenkeeper

**Comment by lance** [comment]
@lholmquist @helio-frota where do we stand with this? I think I have opened up permissions enough now, but please confirm.

**Comment by helio-frota** [comment]
for me is `ok`, otherwise if I need in a future something related to coveralls or greenkeeper or whatever, then I'll ask for. :+1:
