### ISSUE TITLE
Investigate levee

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#17]
The `levee` packages implements the circuit breaker pattern in Javascript. It's written by the people at PayPal. https://github.com/krakenjs/levee

**Comment by balunasj** [comment]
Related to the microservices demo issue #18

**Comment by lance** [comment]
Took a look at it, and tried to integrate it into [a fork](https://github.com/bucharest-gold/bonjour) of the bonjour app from the MSA demo. While levee looks interesting, I am not sure if it's necessarily the right approach as it is a callback-based API and won't work out of the box with roi, for example, since roi uses promises exclusively.

I also looked at https://www.npmjs.com/package/promise-circuitbreaker which could be useful for us. However, out of the box it uses Bluebird promises, and while it provides an ability to provide your own Promise implementation as a configuration option, the code itself uses non-standard Bluebird functions. Additionally, it's got nowhere near the level of usage of levee, so I'm really not sure if it's right either.

Here are the options I see with regard to #18 going forward.
- Write our own circuit breaker implementation that is optimized for our existing tools and libraries. I don't think this would be a terribly difficult task, but it would definitely take some non-zero amount of effort.
- Fork promise-circuitbreaker and provide some pull requests that make use of more standard compliant Promise APIs.
- Create a levee-promises package that provides an adapter over levee to allow levee's circuit breaker functionality to work with a promise based api.

At the moment, I am leaning towards the first or last option. I worked a bit with promise-circuitbreaker, and while it's fine, I think we'd be better served writing our own or providing a (probably widely useful in the community) promise-levee adapter.

Closing this for now, since I think any further action deserves its own issue.

**Comment by lholmquist** [comment]
@lance should we create issues from those options bullet points?

/me hides if you are already doing that :)

**Comment by lance** [comment]
Mentioning https://github.com/bucharest-gold/entente/issues/18

**Comment by lance** [comment]
@lholmquist I think we need to make an issue for whichever one we decide to do. Of the two I prefer, the last one (levee-promises package) is probably the easiest. I'll start with that as an issue, and if we find it to be a non-optimal solution, we can try one of the others.

**Comment by lance** [comment]
Issue created for the 3rd option, and likely for the 3rd Milestone. https://github.com/bucharest-gold/entente/issues/93
