### ISSUE TITLE
add nodejs-rest-http to greenkeeper

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/entente#172]
https://github.com/bucharest-gold/nodejs-rest-http

**Comment by lance** [comment]
Done:
https://github.com/bucharest-gold/nodejs-rest-http/pull/6

Also, re-enabled for:
https://github.com/bucharest-gold/openshift-rest-client/pull/27

And re-enabled for:
https://github.com/bucharest-gold/nodeshift/pull/64
