### ISSUE TITLE
Define improvements for a version of Burr's Node.js demo microservice [title changed]

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#18]
Some things to improve:
- Add service discovery
- Add circuit breaker
- Modern node version

Title changed from "Implement" to "Define improvements" since implementation is a multi-step process. See additional related work.

Ref: https://github.com/bucharest-gold/entente/issues/93

**Comment by lance** [comment]
https://htmlpreview.github.io/?https://github.com/redhat-helloworld-msa/helloworld-msa/blob/master/readme.html#_install_cdk

**Comment by cesarvr** [comment]
Hi @lance , maybe i can help you with this i wrote this [micro_service](https://github.com/cesarvr/micro_service) kind of project, I'm using it as a template. It has the following stuff: 
- CRUD, you just need pass a collection name he create the complete end-to-end crud.
- It has a simple soap client using node-soap, it does long pulling and has a simple but extendable circuit breaker mechanism. 
- node6
- openshift 3 template and simple docker config file. 

Service discovery is something i haven´t done can be implemented. I will try to keep it up to date.

cheers.

**Comment by lance** [comment]
@cesarvr this is interesting. I will take a look at it and we can talk about what can be done here. Thanks!

**Comment by balunasj** [comment]
Lets move this to Milestone 02, and at least get a better sense of the scope of work, and timing.

**Comment by cmoulliard** [comment]
Here are some ideas that I'm thinking for this project 
- Split the project in different branches or git repos to extend the use case with the patterns like circuit break, service discovery, persistence, ... 
- Use minishift to setup easily the OpenShift platform, create the project & application
- Add a web interface to consult the info
- Replace SOAP with REST services

Here is an excellent entry point to design the solution : https://blog.risingstack.com/moving-node-js-from-paas-to-kubernetes-tutorial/

**Comment by lance** [comment]
@cmoulliard @cesarvr these are great suggestions. But for this issue, I want to keep the scope a little more narrow. Specifically, I want to improve on the `bonjour` node.js component in this project: https://htmlpreview.github.io/?https://github.com/redhat-helloworld-msa/helloworld-msa/blob/master/readme.html#_install_cdk.

I think for an immediate and tangible result, we should consider forking the project https://github.com/redhat-helloworld-msa/bonjour and adding service discovery and circuit breaker capabilities. /cc @balunasj

**Comment by lance** [comment]
So, here is what I see as the defined effort to resolve this issue.
1. Fork https://github.com/redhat-helloworld-msa/bonjour and create 2 separate feature branches, 'service-discovery' and 'circuit-breaker'
2. Integrate [levee](https://github.com/krakenjs/levee) as a circuit breaker implementation
3. Integrate @cesarvr's [microservice-discovery](https://github.com/cesarvr/microservice-discovery) module for service discovery
4. Test against the entire Hello World MSA stack, and provide upstream contributions where necessary in order to ensure our changes to `bonjour` are successful.
5. Submit a PR to the `bonjour` project based on these changes.

We may want to add new GH issues for at least a couple of these tasks. @balunasj what do you think about this as a direction and approach?

**Comment by cmoulliard** [comment]
> what do you think about this as a direction and approach?

+1

**Comment by cesarvr** [comment]
Just a suggestion, I was thinking in a way to decouple the fail over mechanism (circuit breaker) from the client API, i think the following way is an client agnostic way to achieve it, here is a code snippet just to expose the idea: 

``` javascript
'use strict';

let http = require('http');
let roi = require('roi');
let fetch = require('node-fetch');


function cbreaker(strategy) {
   let r = http.request;

http.request = function(options, cb){   //decorating http orr https
    console.log('options-> ', options);

    /*
      - handle timeout, status, breaking, in case that we need to 
         brake we can return a code or use delegation.
      - take meassurments. 
    */
    return r(options, cb);
  }
}

cbreaker({timeout: 4000});
// roi
roi.get({endoint:'http://cesarvr.github.io'})
.then((e, rsp)=> console.log(e, rsp))
.catch((e)=>console.log(e))

//node-fetch
fetch('http://cesarvr.github.io')
.then((e, rsp)=> console.log(e, rsp))
.catch((e)=>console.log(e))

```

I think this way the client library is decouple from our recovery mechanism and is more efficient. what do you think?

**Comment by lance** [comment]
@cesarvr this is an interesting approach. It definitely makes http client agnostic breakers possible. But I've spent a little time looking at levee and one of the things I like about it is that there's no restriction to keep actions to HTTP only. 

Your example, with a little extra levee capability thrown in, would look something like this.

``` javascript
'use strict';

const Levee = require('levee');
const roi = require('roi');

const options = {
    maxFailures: 5,
    timeout: 60000,
    resetTimeout: 30000
};

const roiOptions = {
  'endpoint': 'http://localhost:3000/posts'
};


circuit = Levee.createBreaker(roi.get, options);
circuit.fallback = Levee.createBreaker((p) => console.log(`Failed to execute ${p}`), options);

circuit.run(roiOptions, function (err, req, payload) {
   // If the service fails or timeouts occur 5 consecutive times,
    // the breaker opens, fast failing subsequent requests.
    console.log(err || payload);
});
```

What I like about this is that the action could be anything - not just HTTP - and failures can actually have circuit breakers on their own. Lastly, if we monkey patch Node's builtin `http`, this could have unintended side effects in client code, and would prevent client code from using non-circuit-breaker-enabled `http`.

I think it would be pretty straightforward to either embrace levee, or even implement our own circuit breaker module. It would only be a few hundred lines of code. I suggest levee for this effort just because it will be a quick and simple win over the time required to implement our own.

My 2¢

**Comment by cesarvr** [comment]
Ok, fair enough. :)

**Comment by lance** [comment]
Looked at levee and found that as-is, it is not appropriate. But there are some options. I have outlined them here: https://github.com/bucharest-gold/entente/issues/17#issuecomment-256099287

I'm going to [start with](https://github.com/bucharest-gold/entente/issues/93) creating a levee-promises package that can adapt levee to deal with promises and take it from there.

**Comment by lance** [comment]
Closing for now, as this work has branched into multiple smaller issues.

**Comment by lance** [comment]
@cesarvr I implemented a circuit breaker over the weekend, that I think will do the trick nicely. Here is where it is [configured](https://github.com/bucharest-gold/bonjour/blob/circuit-breaker/bonjour.js#L26-L37) and here is where it is [executed](https://github.com/bucharest-gold/bonjour/blob/circuit-breaker/bonjour.js#L71-L74). I think this should work well.

The circuit-breaker implementation, if you are interested, is not yet published, but will be soon. You can check out the [source code](https://github.com/bucharest-gold/opossum) here.

**Comment by cesarvr** [comment]
@lance  Looks very good, i'll start testing it with some projects and will let you know if any issues.
