### ISSUE TITLE
Potential New Booster Development for RHOAR and/or OpenShift

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#181]
The base set of boosters that will be provided for RHOAR initial GA are excellent for helping the enterprise developer get started using our existing portfolio of middleware products. However, I think there is a market specific for Node.js developers that as yet remains untapped. I would like to start some discussion around possible boosters that will appeal more directly to existing Node.js developers and help to show how OpenShift is a great place for Node developers to run their applications. 

Here is a list of ideas to get us started. Some of these might build on each other to tell a story.

* Social Login - show how easy it is to spin up an application that allows for OAuth with GitHub, Facebook and/or Twitter
* MEAN Stack - Mongo, Express, Angular and Node. This is the goto web development stack for a lot of Node devs. Helio has already begun some work on this.
* Single page app utilizing a public API such as that from [GitHub](https://developer.github.com/v4/) *note that GitHub v4 API is using GraphQL which got some buzz at Node Interactive this year.
* Quick CMS using [Ghost](http://ghost.org) or [Apostrophe CMS](http://apostrophecms.org).
* A React app (need more details here)

Please help contribute to this list and flesh out ideas. We can start by working through some of the immediate questions and potential pitfalls here, and then I will write up a plan for making this happen. Thanks!

**Comment by lholmquist** [comment]
Adding a "Push Server" to the list.

I originally had started something here: https://github.com/lholmquist/Salty-Pig

this was me playing around with getting the AeroGear Unified Push Server(which is a java application) written in node.

I had iOS and Chrome notifications working 2 yrs ago, but it is suffering from bit rot now.

I think there are some concepts here that could be cool to explore, like service discovery.  For example, the different push networks could be there own thing "app" and the "main" application can discover when a new push network is deployed

**Comment by johnfriz** [comment]
There are a lot of really good generator projects on Yeoman (http://yeoman.io/generators/) that could be re-purposed as boosters.

Node integrations with existing middleware products (e.g. A-MQ, JDG, RH-SSO) would also be a great idea (and Node client libs already exist for these products)

**Comment by helio-frota** [comment]
I'm not huge fan of front-end (actually I'm not fan of front-end).
But I want to try to reuse `mea5n-booster-backend` and replace `mea5n-booster-frontend` with [vuejs](https://github.com/vuejs/vue).
I'm a little curious to know if we will have one less step related to edit config files due `ENV vars` (and one less step like the angular build) when using openshift.
https://github.com/bucharest-gold/mea5n-booster#front-end---openshift

btw, I dunno if I can quickly replicate the current layout/style

**Comment by helio-frota** [comment]
vuejs booster here:
https://github.com/helio-frota/vuejs-booster
and some things to be done:
https://github.com/helio-frota/vuejs-booster/issues

at least the layout/style was replicated : ]

![foo](https://user-images.githubusercontent.com/6443576/34959650-2e61dabe-fa16-11e7-9f95-74bbdd9bcb75.png)

**Comment by lance** [comment]
Closing - out of date
