### ISSUE TITLE
RFC - s2i Builder Image for Front-end Javascript

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/entente#187]
### Current Problem

Our current builder image, https://github.com/bucharest-gold/centos7-s2i-nodejs, has been great for "express like" Node apps.  Basically, back-end server applications like REST endpoints.  But there are a lot of users who would like to use our image for their front-end development.  

One of the uses of our builder image that I have seen a lot lately is developers trying to build React or Angular applications and then serve them. It can be done with our image, but there are gotchas and issues that people keep running into. https://github.com/bucharest-gold/centos7-s2i-nodejs/issues/94 , https://github.com/bucharest-gold/centos7-s2i-nodejs/issues/92

Even though these front-end frameworks require node for their build(for babel, webpack, etc...) steps and development servers, the resulting code is just static html/css/javascript that doesn't really need node to server it.

So how do we make front-end developers have a good experience deploying there applications to openshift

### Possible Solution

I think we should consider providing at least one additional builder image that uses our Node.js runtime, but is optimized for an s2i assemble step which builds the application, and a run phase which uses nginx (or other lightweight server) to serve the application.

### Use Cases

A common use case that i've seen people doing for deployments of web apps, is a github webhook, where when a new commit is pushed to github so build pipeline is triggered on Openshift.  

In this case, the build step(from the front-end framework) would need to run, which would need dev depenedencies.  This should all happen in the build/asssemble step. But during the run phase of the application, which happens during the deployment, we just want to setup the http server that serves the static html/css/js files that were created during the assemble step.

If someone is just developing locally and does not want to use the webhook thing, this image should still work.  Either using `nodeshift` or `oc` commands

**Comment by lholmquist** [comment]
Some notes on React Deployment - https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment

**Comment by lholmquist** [comment]
I've started a repo here where i'm going to be experimenting https://github.com/bucharest-gold/centos7-s2i-web-app

it is a copy of https://github.com/bucharest-gold/centos7-s2i-nodejs

**Comment by helio-frota** [comment]
This issue can be closed?

**Comment by lholmquist** [comment]
we now have the web app image
