### ISSUE TITLE
Flush out the node.js guidelines document

### ISSUE THREAD

**Issue by balunasj** [bucharest-gold/entente#19]
The entente node.js coding guidelines document has a solid outline but needs to be flushed out.  We should think about if this document is meant for bucharest-gold, or a general node.js coding guidelines for Red Hat and/or other interested projects.  

https://github.com/bucharest-gold/entente/blob/master/GUIDELINES.md

**Comment by lance** [comment]
@balunasj when you get a chance, please have a look. Feedback welcome.

**Comment by lance** [comment]
@balunasj I've been keeping the guidelines relatively current, and adding things here and there. How about we close this, and when there is a need to add something specific to the guidelines, we can go with a new issue for each thing.

For example, maybe we need an issue to get `szero` usage covered in the guidelines doc - unless @helio-frota has already done it. :)

**Comment by balunasj** [comment]
+1 - closing
