### ISSUE TITLE
Explain a little about what the plot-timer-events

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/entente#26]
Explain a little about what the plot-timer-events tool shows, and how we can use it to optimize our tools/modules.

**Comment by helio-frota** [comment]
> Attempting to use plot-timer-events to generate a graph of v8.log

_python2.7 required_

git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

export PATH=`pwd`/depot_tools:"$PATH"

fetch v8

[hf@archT440 v8]$ du -s -h
1.6G

node -p process.versions.v8

git branch --remotes | grep branch-heads/

git checkout branch-heads/5.0

cd v8/ 

gclient sync

```
tiny hack 1:
cd /usr/lib/
sudo ln -s libtinfo.so.6 libtinfo.so.5
```

```
tiny hack 2:
vim Makefile
GYPFLAGS += -Dlinux_use_bundled_gold=0
[ inspired by :https://bbs.archlinux.org/viewtopic.php?pid=1610923#p1610923 ]
```

make native

export D8_PATH=`pwd`/out/native/

[hf@archT440 v8]$ tools/plot-timer-events --distortion=4500 ~/isolate-0x23d4dc0-v8.log 
         _line 0: undefined variable: Infinity_

**It works with v8.log generated by d8**
![timer-events](https://cloud.githubusercontent.com/assets/6443576/18004699/ea0b2b7a-6b6b-11e6-8d6e-f8510316438d.png)

**Comment by balunasj** [comment]
Is the outcome of this issue a document, blog post, etc...?  

I think shifting to "unscheduled" for now make sense.

**Comment by helio-frota** [comment]
Great move.
- The outcome is a document on entente.
- This is not part of our javascript layer tasks, so no plans for this.

**Comment by lance** [comment]
https://www.chromium.org/developers/creating-v8-profiling-timeline-plots
