### ISSUE TITLE
Consuming Java API's using node.js

### ISSUE THREAD

**Issue by cesarvr** [bucharest-gold/entente#29]
# Ella

Just working in this Node.js native plugin done in C++11 that allows you to load and run Java classes in Javascript, enabling you for example to use Java libraries (PDFBox, Lucene, etc..) in your Node.js code. 
## Features
- You can create Java classes. 
- Send any Java method call to a background thread and handle the response with a JS [callback](https://github.com/cesarvr/Ella#async-call). 
- It detect method overloading, you can target various method signature. 
- JVM to JS exception handling.
- Fast, It cache native reference, saving some JVM lookup time.  
## Need to be done.
- Non-empty constructor. 
- Static class support. 

For now i have test this plugin successfully with JDK 1.7 and JDK 8. If you want to give it a try just go to this [repo](https://github.com/cesarvr/Ella#async-call).

**Comment by balunasj** [comment]
What is the action associated with this issue?  What needs to be done?

**Comment by balunasj** [comment]
We're going to close this issue for now, and please re-open if there are more actions or reviews wanted.
