### ISSUE TITLE
Review AMPQ client/server node library RHEA

### ISSUE THREAD

**Issue by balunasj** [bucharest-gold/entente#32]
Gordon Sim has asked if we could provide him any feedback/comments on https://github.com/grs/rhea the AMPQ node library he's developed.

**Comment by helio-frota** [comment]
Project structure:
- Missing lint. 
  [eslintrc.json](https://github.com/bucharest-gold/automatic-pancake/blob/master/.eslintrc.json)
  [lint script](https://github.com/bucharest-gold/automatic-pancake/blob/master/package.json#L7)
  [lint dependencies](https://github.com/bucharest-gold/automatic-pancake/blob/master/package.json#L24-L29)
  [Makefile lint task](https://github.com/bucharest-gold/automatic-pancake/blob/master/Makefile#L11)
- Missing 'files section'.
  [files section](https://github.com/bucharest-gold/genet/blob/master/package.json#L6-L12)
- Missing CI support.
  [Travis example](https://github.com/bucharest-gold/automatic-pancake/blob/master/.travis.yml)
- package.json - 'scripts section' using undeclared dependencies:
  "mocha","istanbul,"browserify"
- Missing .gitignore
  [ignore node_modules](https://github.com/bucharest-gold/automatic-pancake/blob/master/.gitignore#L1)

Documentation:
- Missing information 'how to run/test' for development.
  [Contributing guide](https://github.com/bucharest-gold/automatic-pancake/blob/master/CONTRIBUTING.md)

Code:
- Some unused variables.
- Function names using underline instead camelCase.
- Using var instead ES6 let and const.
- Some global variables.
- Heavy 'this' usage.
- Mix single and double quotes.
- Magic numbers.
- Missing ';' sometimes.

Style:
- {} on the same line.
- Missing blank lines between functions.
- Long lines
- Spaces

Dev cycle:
- Not able to run the tests with 'npm run test'.

**Comment by lance** [comment]
Looks good @helio-frota. Thanks! 

I've updated the GUIDELINES.md document to address some of your points in the 'Code' and 'Style' sections here. https://github.com/bucharest-gold/entente/blob/master/GUIDELINES.md#some-things-linting-will-catch

@grs Helio has looked through your code and found a number of issues related to our "standard" recommendations for node projects. Have a look here, and we'd be happy to discuss with you. 

Thanks!

**Comment by helio-frota** [comment]
_'Some things linting will catch'_ 
true !
@lance :+1:

**Comment by grs** [comment]
Thanks! I'll start going through these soon (I'm on PTO from 21st for a bit, so will likely be when I get back).

**Comment by lance** [comment]
This looks like it can be closed. Or is there more that needs to be done here?

**Comment by balunasj** [comment]
Yeah, I think this can be closed.  @grs if you would like more help or reviews just open/re-open an issue and ping us on the mailing list!
