### ISSUE TITLE
Review jvm-npm per B/G guidelines and bring into compliance

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#33]
The package is here. https://www.npmjs.com/package/jvm-npm
The repo is here. https://github.com/nodyn/jvm-npm

It has only ever been released once, but there are people using it. Let's make it live up to the bucharest-standards, eh?

After applying at a minimum the following items from our guidelines doc, we should publish a new release.
- [x] Continuous integration with Travis-CI
- [x] `package.json` `files` property
- [x] Code-style/linting

This is a bit of a strange case, because it's meant to run on a JVM Javascript runtime - e.g. nashorn, rhino and dynjs. So with the exception of `npm publish` the build is actually maven.

**Comment by helio-frota** [comment]
done ?

**Comment by lance** [comment]
TY
