### ISSUE TITLE
Publish a blog on szero

### ISSUE THREAD

**Issue by balunasj** [bucharest-gold/entente#35]
Include those sexy screenshots and how others could use the tool to check their own dependencies.

**Comment by lance** [comment]
@balunasj do you think we should have a team blog? Or do you prefer for individuals to maintain their own and syndicate with JBoss?

**Comment by balunasj** [comment]
I'm very open to either approach.  I've always wanted to have my own blog site, but never got around to it.  I wonder what is available if we did want a team blog - tools, open source, etc...

**Comment by lance** [comment]
Personally, I prefer to just use some static site generator and run our own website like wildfly-swarm does, but I'm not sure we have enough to say at this point to warrant a standalone site. What would the focus of the site even be? 

I know @lholmquist has his own personal blog. Not sure about @helio-frota. On my personal site, even though it's a one-pager, I'm using metalsmith, so it would be relatively straightforward for me to set up a blog. But honestly, I have pretty much zero traffic to my personal site, so I'm not sure that writing in a void is the best idea.

There are 3rd party sites like medium.com which we might want to consider. But honestly, as I write this, it seems like we should just have a team site where we can publish (and/or syndicate if @lholmquist wants to continue to just write on his own blog). This would give all of our efforts a greater sense of cohesion when we write about them. But I guess, again, I keep coming back to the question of what the site would really be about. What is our identity?

Should we open an issue that's just about figuring this out?

**Comment by lance** [comment]
FWIW, I did start to set up a website a while back https://github.com/bucharest-gold/bucharest-gold.github.io

But I ran into that question, "what do we want to say on the website?" and decided that bucharest-gold/entente was enough for the time being.

**Comment by lholmquist** [comment]
My blog is running Ghost which runs on Openshift,  and i don't really think i get much traffic there either.  But i'll write where ever we decide

**Comment by lholmquist** [comment]
blog is live,  http://blog.lholmquist.org/checking-dependencies-with-szero/

**Comment by balunasj** [comment]
We need to be emailing nodejs-interest list with these blogs as well!  Share the love :-)

**Comment by lholmquist** [comment]
just shared :)
