### ISSUE TITLE
Node Core collaborator, and general involvement

### ISSUE THREAD

**Issue by balunasj** [bucharest-gold/entente#38]
Tracking issue for our ongoing Node.js upstream collaboration efforts.

[edit: simplified description]

**Comment by lance** [comment]
### @lance
- **[Commits](https://github.com/nodejs/node/commits/master?author=lance)**
- **[Comments](https://github.com/nodejs/node/issues?utf8=%E2%9C%93&q=commenter%3Alance+)**
- **[Open PRs](https://github.com/nodejs/node/search?utf8=%E2%9C%93&q=author%3Alance+is%3Apr+is%3Aopen&type=Issues)**
- **[Closed PRs](https://github.com/nodejs/node/search?utf8=%E2%9C%93&q=author%3Alance+is%3Apr+is%3Aclosed&type=Issues)**

**Comment by danbev** [comment]
### [@danbev](https://github.com/danbev)

## Node
- [Commits](https://github.com/nodejs/node/commits/master?author=danbev)
- [Comments](https://github.com/nodejs/node/issues?utf8=%E2%9C%93&q=commenter%3Adanbev+)
- [Open PRs](https://github.com/nodejs/node/pulls/danbev)
- [Closed PRs](https://github.com/nodejs/node/pulls?q=is%3Apr+author%3Adanbev+is%3Aclosed)

## [Nodejs.org](https://github.com/nodejs/nodejs.org)
- [Commits](https://github.com/nodejs/nodejs.org/commits/master?author=danbev)
- [Comments](https://github.com/nodejs/nodejs.org/issues?utf8=%E2%9C%93&q=commenter%3Adanbev+)
- [Open PRs](https://github.com/nodejs/nodejs.org/pulls/danbev)
- [Closed PRs](https://github.com/nodejs/nodejs.org/pulls?q=is%3Apr+author%3Adanbev+is%3Aclosed)

**Comment by lholmquist** [comment]
### [@lholmquist](https://github.com/lholmquist)

## 
- [Commits](https://github.com/nodejs/node/commits/master?author=lholmquist)
- [Comments](https://github.com/nodejs/node/issues?utf8=%E2%9C%93&q=commenter%3Alholmquist+)
- [Open PRs](https://github.com/nodejs/node/pulls/lholmquist)
- [Closed PRs](https://github.com/nodejs/node/pulls?q=is%3Apr+author%3Alholmquist+is%3Aclosed)

**Comment by helio-frota** [comment]
### [@helio-frota](https://github.com/helio-frota)

## 
- [Commits](https://github.com/nodejs/node/commits/master?author=helio-frota)
- [Comments](https://github.com/nodejs/node/issues?utf8=%E2%9C%93&q=commenter%3Ahelio-frota+)
- [Open PRs](https://github.com/nodejs/node/pulls/helio-frota)
- [Closed PRs](https://github.com/nodejs/node/pulls?q=is%3Apr+author%3Ahelio-frota+is%3Aclosed)

**Comment by lance** [comment]
Closing - out of date
