### ISSUE TITLE
Consider implementing a node client for the WildFly DMR API

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#6]
Ref: https://github.com/hal/dmr.js
Ref: http://hpehl.info/independent-jboss-admin-console.html

**Comment by lholmquist** [comment]
Adding in the link for the Wildfly HTTP management API

https://docs.jboss.org/author/display/WFLY10/The+HTTP+management+API

**Comment by helio-frota** [comment]
More operations:
http://www.mastertheboss.com/jboss-server/jboss-script/managing-jboss-wildfly-using-httpjson-api

**Comment by helio-frota** [comment]
More operations:
http://middlewaremagic.com/jboss/?p=2488

**Comment by helio-frota** [comment]
Some work started:
https://github.com/bucharest-gold/ndmr

The idea is to 'translate' the [dart](https://github.com/hal/dmr.dart/) version to javascript

**Comment by balunasj** [comment]
Implementing this is likely a complex and large job, and Lance and I are wondering if there is strong enough demand from the Wildfly team for this functionality.  

@lance is going to follow up with the original post and see what sort of demand is on this work.

**Comment by helio-frota** [comment]
Great move!

...and risky : https://github.com/bucharest-gold/ndmr/issues/18

**Comment by lance** [comment]
@balunasj I've emailed Galder who was originally asking for this, but have not heard back. Unless we want to reach out directly to the WildFly team, I'd say this is done. There doesn't seem to be great demand for it.

**Comment by lance** [comment]
I am closing this for now, and if we find that there is a demand for a DMR client, we can pick it back up with a new issue.
