### ISSUE TITLE
Fill Hawkular-APM with Lightbright traces

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#7]
- [ ] Finish the data mapping between [lightbright](https://github.com/bucharest-gold/lightbright) and hawkular-apm json.
- [x] Avoid trace data polution on hawkular-apm-server from [roi](https://github.com/bucharest-gold/roi) module.

**Comment by helio-frota** [comment]
More information:
https://github.com/bucharest-gold/entente/issues/11

**Comment by lance** [comment]
Ref: https://github.com/bucharest-gold/lightbright/milestone/1

**Comment by helio-frota** [comment]
Now is more easy to identify any difference from roi trace data
https://github.com/bucharest-gold/hawkular-apm-client/issues/5#issuecomment-251521418

Instead send to hawkular-server:
https://github.com/bucharest-gold/hawkular-apm-client/blob/master/index.js#L70

We send to console.log();

Because the FakeApp is calling `publishTraces` here:
https://github.com/bucharest-gold/hawkular-apm-client/blob/master/test/app-fixture.js#L24

Then we can see if has any difference with roi usage.

**Comment by helio-frota** [comment]
https://gist.github.com/helio-frota/2e287c3b22a275e9a8e5762571cf6e37

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/entente/issues/7#issue-157981942
We don't need to worry about this anymore, all the tests are showing the same thing please see the gist ^^

**Comment by helio-frota** [comment]
From lance:
https://github.com/bucharest-gold/entente/issues/11#issuecomment-251948740

We are using these attributes:
https://github.com/bucharest-gold/hawkular-apm-client/blob/master/index.js#L51-L62

**Comment by helio-frota** [comment]
When accessing the example App multiple times, then new wrapers/handlers arise.

I have no idea if this is correct/expected:
https://gist.github.com/helio-frota/bf11e2409fa908c7eda2cb0dd37522f3

Every time the text appears on the gist is one access to example app url:
"Traces added to hawkular-apm-server."

**Comment by helio-frota** [comment]
![a](https://cloud.githubusercontent.com/assets/6443576/19171627/281816c8-8bf4-11e6-919b-f3dbbe84b605.png)
![b](https://cloud.githubusercontent.com/assets/6443576/19171630/2b2055ec-8bf4-11e6-8881-7358a982c128.png)

**Comment by lance** [comment]
After discussing this with @balunasj we've decided to close this issue, and track progress towards this in bucharest-gold/lightbright since the implementation of any given data format would probably be most efficiently accomplished as a lightbright filter. See: https://github.com/bucharest-gold/lightbright/issues/11.
