### ISSUE TITLE
.npm-init.js should we use fixed dev dependencies versions?

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/entente#82]
So currently for the devDeps we use just `*` for the versions https://github.com/bucharest-gold/entente/blob/master/npm-init.js#L68

besides nsp, I wonder if we should "fix" those version to something specific?

The downside is we would need to update the versions at some interval when they are updated.

I feel like the best practice in this case would be to use an actual version

@lance @balunasj @helio-frota  any thoughts?

**Comment by helio-frota** [comment]
true.

Until now, I saw only 2 problems: handlebars [used by huilu] and istanbul.

'*' adds risk. Small amount of incidents maybe, but when happen is really not good.

I  vote for  :

> The downside is we would need to update the versions at some interval when they are updated.

**Comment by lance** [comment]
Hmm - I don't like using `*`. That's just asking for trouble. I think updating version numbers as these tools mature is not too onerous. There are only a handful to keep track of. We could try to do this manually, or use something like [sibbell](https://sibbell.com/start/) or [versioneye](https://www.versioneye.com/) to manage that for us. In either case, we should probably be using patch-level change ranges, e.g. `~0.1.3`.

**Comment by lholmquist** [comment]
@lance @helio-frota thanks for the input,  i'll update the file for the next milestone

**Comment by lholmquist** [comment]
versions added in this commit: c6171b4
