### ISSUE TITLE
Check out Yarn

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/entente#86]
The new package manager client for node modules.  We should probably check it out

https://code.facebook.com/posts/1840075619545360

https://yarnpkg.com/en/compare

https://yarnpkg.com/

**Comment by lholmquist** [comment]
One of the things specifically i want to see, is how they are doing the "init" thing.  Do they also use a ".npm-init.js" file?

**Comment by balunasj** [comment]
Shifting to unschedule for now.  If we feel we're "done" with this, lets close it.

**Comment by lance** [comment]
I think we are done with this. There's nothing to do with it, really. I'm closing. If you get a yarn to try yarn again, feel free to reopen.
