### ISSUE TITLE
Run npm install at the end of the .npm-init.js file

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/entente#88]
I'm sure it is possible.  I wonder if we should add this.  Our custom .npm-init.js file specifies dependecies, so it would save an extra step of having to do the install

@lance @helio-frota @balunasj thoughts?

**Comment by helio-frota** [comment]
> save an extra step

:+1:

**Comment by lance** [comment]
Makes sense, I think. Although it'd be nice to turn this off with a flag. The `npm` command doesn't seem to barf if you supply it with an unknown option, and we've got access to `process.argv` to look for it. So we could have something like `--no-install` and `-n` to prevent automatic installation.

**Comment by lholmquist** [comment]
yea,  i was thinking the same thing wrt the flag for turning off auto-install.

**Comment by helio-frota** [comment]
Until now I can't find a way to run things after npm init finish.
We need this to install things after package.json create.
