### ISSUE TITLE
Assist Hawkular Team with an OpenTracing JS provider

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#89]
Pavol Loffay will be doing the work for the hawkular team. Our duties should include code reviews and general guidance.

**Comment by lance** [comment]
@objectiser can you help me understand how the work you are doing in creating a node.js open tracing adapter differs from the work we have started experimenting with here: https://github.com/bucharest-gold/hawkular-apm-client. Does it make sense to have both projects? Should one consume the other? Sorry for all of the questions. I'm just trying to get my head around what we can do to help and where we should get out of the way if that's the case. 

Edit: 
@balunasj including you in this conversation, since you might have some ideas here as well

**Comment by objectiser** [comment]
@lance I think it probably makes sense for the hawkular-apm-client project to consume the opentracing provider - so the hawkular-apm-client would provide the glue between lightbright and the opentracing api. I've started a similar effort to look at replacing our previous javaagent with one that is simply using byteman rules above the opentracing api.

**Comment by pavolloffay** [comment]
Hello @lance @balunasj!

Now I'm starting with the opentracing-javascript implementation. I have a question do we need to create a separate repository for this package or is the https://github.com/hawkular/hawkular-apm fine to use? I'm asking because we would like to publish it to npm later.

**Comment by pavolloffay** [comment]
The first benefit what I see when using a separate repository is `Travis CI`, which we will need.

**Comment by lance** [comment]
@pavolloffay if it were my project, I would want the node.js connector to live within its own repository.
@objectiser thanks for the feedback.

**Comment by objectiser** [comment]
@lance No problem.

+1, I think a separate repo would also help with community contributions, as they would only be having to deal with a small well defined project that is js/node focused, rather than a larger repo with multiple languages.

**Comment by pavolloffay** [comment]
@lance Here is the repository with the firts PR https://github.com/hawkular/hawkular-apm-opentracing-javascript/pull/1 Could you please review it?  I'm not sure if we need to add you to the repo or you can review without it.

**Comment by lance** [comment]
OK - quick review done. :)

**Comment by balunasj** [comment]
We're going to go ahead and close this issue for now, but any additional reviews, questions, or assistance please open a new issue.  We're quite curious to see the final output as well.
