### ISSUE TITLE
Create guidelines for optimizing Javascript on V8

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/entente#9]
Our current plan on this issue is to write test cases to get results **based** on:
**1.** Our doubts and project needs
**2.** Try to cover affirmations like  'Don't  do X, don't do Y'
example: "Don't use prototypes because this has a bad performance"

The repository for the tests: https://github.com/bucharest-gold/perf-quest

So we can add resources (links, videos, etc) on comments here to catch and solve the item **2.** ^

**Comment by helio-frota** [comment]
> Resources / blogs / Videos / etc - To check and write test cases on perf-quest.
- http://debuggable.com/posts/understanding-hidden-classes-in-v8:4c7e81e4-1330-4398-8bd2-761bcbdd56cb
- https://www.smashingmagazine.com/2012/11/writing-fast-memory-efficient-javascript/
- https://gist.github.com/twokul/9501770
- https://coderwall.com/p/kvzbpa/don-t-use-array-foreach-use-for-instead

**Comment by cesarvr** [comment]
I think this talk can be useful: 

[Javascript V8 vs C++ Fibunacci](https://www.youtube.com/watch?v=UJPdhx5zTaw)

**Comment by helio-frota** [comment]
@cesarvr thanks for the video link.

**Comment by cesarvr** [comment]
no problema 👍

**Comment by helio-frota** [comment]
So, **according item 2.** (first comment on this issue ^)
The video starts at 10:30
10:30 - 15:30 about hidden classes  [ we already have a test case for this ]
Then the video shows some 'don'ts':

>  Don't pre-allocate large Arrays (e.g > 64k elements) to their maximum size, instead grow as you go.
>  Don't delete elements in arrays, specially numeric arrays.
>  Don't load uninitialized or deleted elements.
>  Don't store non-numeric values (objects) in numeric arrays.

Then from 26:30 to the end, are more related to compiler optimization, deoptimization and prof.

So I think the 'don'ts' can be added to code_recomendations in a future.

**Comment by helio-frota** [comment]
This blog post is basically the summary of this ^ video :
https://www.html5rocks.com/en/tutorials/speed/v8/
Also, to be clear, the video is not about performance **JS vs C++ Fibonacci**.

**Comment by helio-frota** [comment]
According @lance 

The idea is to have a file on entente root, called CODE_RECOMENDATIONS.md

This file will link with all test cases from https://github.com/bucharest-gold/perf-quest

@lholmquist and @lance will help on this document.

With more attention for the cases where we have 'BASICALLY THE SAME' performance.
Writing why use X instead Y since performance are the same.

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/entente/blob/master/CODE_RECOMMENDATIONS.md

**Comment by helio-frota** [comment]
hi folks, the concept of this issue is done. 
Just to remember that this is a endless issue.
