### ISSUE TITLE
Review conventional-changelog and friends

### ISSUE THREAD

**Issue by lance** [bucharest-gold/entente#90]
We should consider adding a process that uses these tools to our projects and guidelines.

https://github.com/conventional-changelog/standard-version - Automatic version and CHANGELOG management

https://github.com/bcoe/conventional-changelog-standard/blob/master/convention.md - Commit standards that make CHANGELOG management easily automated

https://github.com/conventional-changelog/conventional-changelog-cli - Generate a CHANGELOG from git metadata (e.g. the standards noted above)

**Comment by helio-frota** [comment]
https://www.npmjs.com/package/test-ccsv
Tested our npm script with the correct github user `npm init -y`.
Also tested the conventional-changelog.
Currently I have only one concern:
Our npm script is creating version 0.0.1, and when we run standard-version, it bump to 1.0.0.

But is working really fine, changelog generated: 
https://github.com/panther-js/test-ccsv/blob/master/CHANGELOG.md

More informations about version numbers
https://github.com/conventional-changelog/standard-version/issues/132
https://github.com/conventional-changelog/standard-version/issues/131

Also, according my understanding, it will force us to always fork the projects due squash/merge option on github.

**Comment by helio-frota** [comment]
npm-init 
https://github.com/bucharest-gold/entente/blob/master/npm-init.js#L55
https://github.com/bucharest-gold/entente/blob/master/npm-init.js#L81

https://github.com/bucharest-gold/entente/blob/master/GUIDELINES.md#release-with-automatic-changelog-generation

**Comment by helio-frota** [comment]
@lance this can be closed ?

**Comment by lance** [comment]
Integrated to recommendations and npm-init.js here https://github.com/bucharest-gold/entente/commit/b975728004a2359ceb81c97f88e6dcc7108ed04a
