### ISSUE TITLE
Lifecycle methods for npm init command

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/entente#92]
Sort of related to here:  https://github.com/bucharest-gold/entente/issues/88

Perhaps we can look into adding some lifecycle methods into the npm init command.

There are a couple projects that make up the npm init command besides just "npm", i believe they are https://github.com/npm/promzard for the prompting and https://github.com/npm/init-package-json.

We could investigate adding something in, like "pre-init" or "post-init"

**Comment by helio-frota** [comment]
Closing this.
This is related to https://github.com/bucharest-gold/entente/issues/127#issuecomment-437118117
